<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="MUMTEWD00052" name="Command line test 6eb7c0b0-0a3c-4ddf-bf4e-aefcb67e5c61" tests="1" failures="1" timestamp="29 Mar 2018 07:02:14 GMT" time="0.13" errors="0">
  <testcase name="@AfterClass quitbrowser" time="0.0" classname="com.HReckAutomation.HReck.forgotPassword">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.HReckAutomation.CommonUtils.CommonUtilities.AccessToHReckURL(CommonUtilities.java:56)
	at com.HReckAutomation.HReck.forgotPassword.quitbrowser(forgotPassword.java:29)
	at com.mentorstudies.automationframework.TestRunner.main(TestRunner.java:117)
	at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:294)
	at java.lang.Thread.run(Thread.java:748)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- @AfterClass quitbrowser -->
  <testcase name="forgotPasswordMain" time="0.005" classname="com.HReckAutomation.HReck.forgotPassword">
    <failure type="org.testng.TestNGException" message="
The data provider is trying to pass 0 parameters but the method com.HReckAutomation.HReck.forgotPassword#forgotPasswordMain takes 2 and TestNG is unable in inject a suitable object">
      <![CDATA[org.testng.TestNGException: 
The data provider is trying to pass 0 parameters but the method com.HReckAutomation.HReck.forgotPassword#forgotPasswordMain takes 2 and TestNG is unable in inject a suitable object
	at com.mentorstudies.automationframework.TestRunner.main(TestRunner.java:117)
	at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:294)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 0
	... 21 more
... Removed 20 stack frames]]>
    </failure>
  </testcase> <!-- forgotPasswordMain -->
</testsuite> <!-- Command line test 6eb7c0b0-0a3c-4ddf-bf4e-aefcb67e5c61 -->
